import type { Metadata } from "next";
import { Children } from "react";
import styles from "./page.module.scss";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={styles.main}>
      <Image
        alt="healthcare"
        src="/images/healthcareBackground.jpg"
        layout="fill"
        objectFit="cover"
        unoptimized
      />
      <div className={styles.loginBox}>
        <div className={styles.imgBox}>
          <Image
            className={styles.medcyImage}
            src="/images/medcy.png"
            width={450}
            height={450}
            style={{ backgroundColor: "transparent" }}
            alt="Medcy"
            unoptimized
          />
        </div>
        <div className={styles.contents}>
            {children}
        </div>
      </div>
    </main>
  );
}
