import type { Metadata } from "next";
import styles from "./layout.module.scss";
import Nav from "@/components/Nav/Nav";
import PageTemplate from "@/components/PageTemplate/PageTemplate";

import PageComponent from "@/components/PageTemplate/PageComponent/PageComponent";
import AuthProvider from "@/components/shared/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <main className={styles.Main}>
      <AuthProvider>
        <Nav />
        <PageTemplate>{children}</PageTemplate>
      </AuthProvider>
    </main>
  );
}
