
import TreatmentPlansSubNav from "@/components/PageTemplate/PageComponent/treatmentPlans/treatmentPlansSubNav/TreatmentPlansSubNav";
import styles from './layout.module.scss';
import type { Metadata } from 'next';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

 export default function Layout({children,}:{children: React.ReactNode;}){
      
    return(
      <div className={styles.container}>
      <TreatmentPlansSubNav/>
       {children}
      </div>
      );
 }

