import type { Metadata } from "next";
import styles from "./layout.module.scss";

export const metadata: Metadata = {
  title: "Create Next Appqqq",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className={styles.main}>
      <nav className={styles.nav}>{}</nav>
      <div className={styles.page}>
        <div className={styles.sideBar}></div>
        <div className={styles.contents}>{children}</div>
      </div>
    </main>
  );
}
