
import type { Metadata } from "next";
import styles from "./layout.module.scss";
import Nav from "@/components/Nav/Nav";
import PageTemplate from "@/components/PageTemplate/PageTemplate";
import SideMenu from "@/components/SideMenu/SideMenu";
import PageComponent from "@/components/PageTemplate/PageComponent/PageComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className={styles.Main}>
      <Nav/>
      <PageTemplate node = {children} />
    </main>
  );
}
